### ISSUE TITLE
rosa for Ros2 

### ISSUE THREAD

**Issue by josh-001** [nasa-jpl/rosa#23]
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from rosa import ROSA

load_dotenv()  # This loads the variables from .env file

openai_llm = ChatOpenAI(
    model_name="gpt-4o",  # or your preferred model
    temperature=0,
    max_tokens=100,
    timeout=None,
    max_retries=2,
    openai_api_key=os.getenv("OPENAI_API_KEY"),  # Using environment variable
)

rosa_instance = ROSA(ros_version=2, llm=openai_llm)
rosa_instance.invoke("Show me a list of topics")

#  issue i am facing
when i am running this example its not printing anything any changes i have to do?
i tried with running a talker node also
![Screenshot from 2024-09-12 12-24-32](https://github.com/user-attachments/assets/b1cb8eac-c47a-4e1b-ac1d-37c7140d3879)

**Comment by RobRoyce** [comment]
Interesting. Can you verify that invoking the `ChatOpenAI` instance works?

e.g.

```python
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from rosa import ROSA

load_dotenv() # This loads the variables from .env file

openai_llm = ChatOpenAI(
    model_name="gpt-4o",
    temperature=0,
    max_tokens=100,
    timeout=None,
    max_retries=2,
    openai_api_key=os.getenv("OPENAI_API_KEY")
)

openai_llm.invoke("what is the capital of France?")

**Comment by josh-001** [comment]
yes, i tried doing that i dont have token to run the gpt-4o so its throwing the error,you can see below image

![Screenshot from 2024-09-14 12-06-54](https://github.com/user-attachments/assets/7301134b-7f17-46c1-b5b6-09633516dd98)


but when i am invoking with **ROSA** its not even throwing any tokens error.

![Screenshot from 2024-09-14 12-07-36](https://github.com/user-attachments/assets/f88b7709-e5e6-440e-a182-460e4ccb1c74)

**Comment by RobRoyce** [comment]
I see, that's very good information to have. In this case, this is expected behavior. The call to `invoke` does not print the response, rather it returns a string. You can see the response like so:

```python
response = rosa_instance.invoke("Show me a list of topics")
print(response)
```

**Comment by josh-001** [comment]
That made sense now ,thanks for the update
