### ISSUE TITLE
What's The Best Way to Debug?

### ISSUE THREAD

**Issue by sourcesync** [nasa-jpl/rosa#28]
Great robotics repo!

I'm just getting started and I having everything running on MacBooK M2 Sonoma:
* the hardest part was configure an X11 server (XQuartz via brew)
* making sure X11 portforwarding worked via Docker ( I set DISPLAY using my machines IP address )

It's very cool seeing stuff work!

I noticed a couple of odd things perhaps you can help with:

* I could not change the background although the agent seems to have gotten the command (background is still blue).

```
Hi! I'm the ROSA-TurtleSim agent 🐢🤖. How can I help you today?
Try help, examples, clear, info or exit.
> change the background color to red
╭────────────────────────────────────────────────────────────────────────────────── Final Response ───────────────────────────────────────────────────────────────────────────────────╮
│ The background color has been changed to red successfully. If you have any more color changes or tasks in mind, feel free to let me know!                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

* When the display pops up, there is initially a turtle but no command makes it do anything.  I managed to get a new turtle to appear and it seems to take the various move and teleport commands.

Finally, what's the best way to debug these things other than sprinkling print statements throughout the code?  "Read The Source" is a perfectly valid answer.

Thanks - and great project!

**Comment by RobRoyce** [comment]
Thanks for the feedback. I saw your PR for macOS instructions (open then closed) and appreciate the effort!

For the background, there's a known issue with ROS1 where you have to do a sim reset (call the `/reset` service) to have it take effect. You can try something like "change the background to red, then reset the sim." I never experienced the second error, but I'm wondering if maybe the turtle name is not correct?

One of the best/easiest ways to debug is to set `verbose=True` so you can see the intermediate reasoning/observation steps. That should give you some insight into how/why the tools are being called (along with the actual tool calls and their parameters).

Hope this helps!

**Comment by sourcesync** [comment]
Hey Rob,

Thanks for your response!

Yeah, so we forked your repo (https://github.com/alfredc12/rosa) and by
mistake my PR was submitted to your repo instead of the fork.

We will probably submit our cumulative changes to your repo as one big PR
at some point.

( I'm personally interested in embedded agentic LLMs and so I'm trying out
some ideas around ternary LLMs eventually targeted to FPGAs, and your
simulation environment is a perfect playground before committing to the
hardware work )

Thanks for the pointers on debugging!

**Comment by RobRoyce** [comment]
Going to close this one out as resolved, but please feel free to comment if you think it should be re-opened.
