### ISSUE TITLE
[Bug]: rosa-turtlesim-demo not working on WSL 2 - Ubuntu 22.04.5 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by giuseppe-coco** [nasa-jpl/rosa#38]
I'm trying to replicate the `rosa-turtlesim-demo` but i was stuck when i ran `demo.sh`. 
The scripts prints `Enabling X11 forwarding...` and then It no longer goes on. it's as if script were frozen.

**My environment**

- WSL 2
- Ubuntu 22.04.5 LTS (Jammy Jellyfish)
- At first, i got `Error: X11 forwarding is not working. Please check your X11 server and try again.` so i installed X11 with `sudo apt install -y x11-xserver-utils`.

**Comment by RobRoyce** [comment]
ROSA hasn't been tested or verified on Windows or WSL2. Happy to work with you on this to figure out how we can support it.

Can you give me some more details about your setup? Are you simply running the `demo.sh` script in WSL 2? Do you have Docker running inside of WSL 2?

My go-to method for checking X11 is to install `x11-apps` and run `xeyes`. If that doesn't work, then the ROSA demo (with TurtleSim) won't work either.

**Comment by giuseppe-coco** [comment]
Hi!
Sorry for the late response but the email related to your message ended up in the spam tab.
I tried to fix the error today but I haven't found anything that resolve it.
On WSL, `xeyes` works properly. 

Now actually the issue is the following:

```shell
$ ./demo.sh
Enabling X11 forwarding...
xhost:  unable to open display "host.docker.internal:0"
Error: X11 forwarding is not working. Please check your X11 server and try again.
```
I thought the issue could be that `host.docker.internal:0` wasn't inside `/etc/hosts`.
So I used Docker Desktop setting 
`Add the *.docker.internal names to the host's /etc/hosts file. Lets you resolve *.docker.internal DNS names from both the host and your containers.` to address it but  `/etc/hosts` hasn't updated so I updated it manually but I still got the same errors 
```shell
xhost:  unable to open display "host.docker.internal:0"
Error: X11 forwarding is not working. Please check your X11 server and try again.
```

Then, from Docker Desktop settings i setted 
`
Enable host networking.
Host networking allows containers that are started with --net=host to use localhost to connect to TCP and UDP services on the host. It will automatically allow software on the host to use localhost to connect to TCP and UDP services in the container.
`
I still didn't fix the issue.

I tried 
```shell
        export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
```
but i got
```shell
xhost:  unable to open display "10.255.255.254:0"
Error: X11 forwarding is not working. Please check your X11 server and try again.
```
ChatGPT suggests, among other things, to install VcXsrv on Windows but is It sounds strange to me to have to install another X server since all the xapps already work. 
In my opinion it's an internal network problem.

**Comment by giuseppe-coco** [comment]
I think I resolved it.

Using WSL, `host.docker.internal` resolver is not present inside `/etc/hosts` file of the linux distro. It's among dns resolver of windows, inside `C:\Windows\System32\drivers\etc\hosts`.
So export `DISPLAY=host.docker.internal:0` won't work. In that case, `I'll use export DISPLAY=:0`

**Comment by RobRoyce** [comment]
Nice catch, and thanks for the PR and fix!

**Comment by giuseppe-coco** [comment]
pleasure
