### ISSUE TITLE
MicroROS?

### ISSUE THREAD

**Issue by samuk** [nasa-jpl/rosa#52]
I have a little bot where all the ROS2 compute happens on a users laptop:  https://rosmo-robot.github.io/ on-robot is just a pair of esp32s3, one for control/motors and one for streaming audio/video.

If I got ESP32s3 cam one streaming audio using https://github.com/ROSMicroPy/ROSMicroPy/tree/main would it be feasible to interact with your codebase?

Or would the latency be a problem?

**Comment by RobRoyce** [comment]
You can run ROSA on any device with internet that has ROS installed, as long as the `ROS_MASTER_URI` environment variable is set correctly. 

In your case, I would advise running it on the laptop. You can use the [`audio_common`](https://wiki.ros.org/audio_common/Tutorials/Streaming%20audio) message to stream from the ESP32s3 and interact with any API on the laptop.
